### ISSUE TITLE
Feature: Add a GitHub Actions workflow for documentation site deployment. 

### ISSUE THREAD

**Issue by prjctimg** [prjctimg/huetiful#79]
This issue came from [this](https://github.com/prjctimg/huetiful-docs/pull/3#issuecomment-1794193179) pull request which failed to pass build tests. It would be nice to have a workflow that logs the deployment results where everyone can see them (in the Actions tab)

**Comment by prjctimg** [comment]
So I've found this tool called tsdoc-markdown which can generate documentation from Typescript source files. 

The tool also has a workflow file to automate the build when we do a PR. 

The docs can then be pushed to the docs repository therefore triggering a redeployment on the site. 

 [Here's the repository](https://github.com/peterpeterparker/tsdoc-markdown)

@takanome-dev Any idea how we can make such a workflow?

**Comment by takanome-dev** [comment]
> @takanome-dev Any idea how we can make such a workflow?
> 
First, try it locally and make a script to generate the docs.
Then, add a new job after `build` in [development/yml](https://github.com/prjctimg/huetiful-docs/blob/main/.github/workflows/development.yml):

```yml
docs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Generate docs
        run: npm run docs

      - name: Commit docs
        uses: EndBug/add-and-commit@v9
        # We don't want to commit documentation changes to main
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          add: .
          default_author: github_actions
          message: '🤖 Documentation auto-update'
```
